[2023-05-26T08:17:25.227+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2015 permission to 509
[2023-05-26T08:17:25.323+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2015 permission to 509
[2023-05-26T08:17:25.393+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2015 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T08:17:25.426+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2015 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T08:17:25.429+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T08:17:25.471+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): from_local_to_gcs_task_2015> on 2023-05-25 00:00:00+00:00
[2023-05-26T08:17:25.484+0000] {standard_task_runner.py:57} INFO - Started process 97 to run task
[2023-05-26T08:17:25.497+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_gcs_dag', 'from_local_to_gcs_task_2015', 'scheduled__2023-05-25T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmpv7khzjil']
[2023-05-26T08:17:25.506+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask from_local_to_gcs_task_2015
[2023-05-26T08:17:25.693+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2015 permission to 509
[2023-05-26T08:17:25.711+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2015 scheduled__2023-05-25T00:00:00+00:00 [running]> on host 0d5f6a8dd67a
[2023-05-26T08:17:26.006+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_gcs_dag' AIRFLOW_CTX_TASK_ID='from_local_to_gcs_task_2015' AIRFLOW_CTX_EXECUTION_DATE='2023-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-25T00:00:00+00:00'
[2023-05-26T08:17:26.080+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcs_dag.py", line 45, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2682, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/Horticulture_2015.parquet'
[2023-05-26T08:17:26.101+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_gcs_dag, task_id=from_local_to_gcs_task_2015, execution_date=20230525T000000, start_date=20230526T081725, end_date=20230526T081726
[2023-05-26T08:17:26.136+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 51 for task from_local_to_gcs_task_2015 ([Errno 2] No such file or directory: '/opt/airflow/Horticulture_2015.parquet'; 97)
[2023-05-26T08:17:26.190+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-26T08:17:26.237+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-26T12:02:49.883+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2015 permission to 509
[2023-05-26T12:02:49.937+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2015 permission to 509
[2023-05-26T12:02:49.988+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2015 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T12:02:50.007+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2015 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T12:02:50.009+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T12:02:50.045+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): from_local_to_gcs_task_2015> on 2023-05-25 00:00:00+00:00
[2023-05-26T12:02:50.054+0000] {standard_task_runner.py:57} INFO - Started process 1243 to run task
[2023-05-26T12:02:50.063+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_gcs_dag', 'from_local_to_gcs_task_2015', 'scheduled__2023-05-25T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmpu9amp3pz']
[2023-05-26T12:02:50.068+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask from_local_to_gcs_task_2015
[2023-05-26T12:02:50.147+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2015 permission to 509
[2023-05-26T12:02:50.162+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2015 scheduled__2023-05-25T00:00:00+00:00 [running]> on host 335f5093005c
[2023-05-26T12:02:50.297+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_gcs_dag' AIRFLOW_CTX_TASK_ID='from_local_to_gcs_task_2015' AIRFLOW_CTX_EXECUTION_DATE='2023-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-25T00:00:00+00:00'
[2023-05-26T12:02:55.099+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-26T12:02:55.130+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=ingest_data_gcs_dag, task_id=from_local_to_gcs_task_2015, execution_date=20230525T000000, start_date=20230526T120249, end_date=20230526T120255
[2023-05-26T12:02:55.220+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-05-26T12:02:55.267+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
