[2023-05-26T08:17:23.858+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T08:17:23.947+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T08:17:24.019+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T08:17:24.047+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T08:17:24.048+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T08:17:24.084+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): from_local_to_gcs_task_2016> on 2023-05-25 00:00:00+00:00
[2023-05-26T08:17:24.102+0000] {standard_task_runner.py:57} INFO - Started process 96 to run task
[2023-05-26T08:17:24.115+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_gcs_dag', 'from_local_to_gcs_task_2016', 'scheduled__2023-05-25T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmp9hvkeyd7']
[2023-05-26T08:17:24.122+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask from_local_to_gcs_task_2016
[2023-05-26T08:17:24.259+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T08:17:24.277+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 scheduled__2023-05-25T00:00:00+00:00 [running]> on host 0d5f6a8dd67a
[2023-05-26T08:17:24.469+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_gcs_dag' AIRFLOW_CTX_TASK_ID='from_local_to_gcs_task_2016' AIRFLOW_CTX_EXECUTION_DATE='2023-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-25T00:00:00+00:00'
[2023-05-26T08:17:24.559+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcs_dag.py", line 45, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2682, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/Horticulture_2016.parquet'
[2023-05-26T08:17:24.583+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_gcs_dag, task_id=from_local_to_gcs_task_2016, execution_date=20230525T000000, start_date=20230526T081724, end_date=20230526T081724
[2023-05-26T08:17:24.611+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 50 for task from_local_to_gcs_task_2016 ([Errno 2] No such file or directory: '/opt/airflow/Horticulture_2016.parquet'; 96)
[2023-05-26T08:17:24.647+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-26T08:17:24.694+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-26T12:02:49.877+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T12:02:49.939+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T12:02:49.992+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T12:02:50.009+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 scheduled__2023-05-25T00:00:00+00:00 [queued]>
[2023-05-26T12:02:50.011+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T12:02:50.043+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): from_local_to_gcs_task_2016> on 2023-05-25 00:00:00+00:00
[2023-05-26T12:02:50.056+0000] {standard_task_runner.py:57} INFO - Started process 1244 to run task
[2023-05-26T12:02:50.064+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_gcs_dag', 'from_local_to_gcs_task_2016', 'scheduled__2023-05-25T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmpficzcilr']
[2023-05-26T12:02:50.069+0000] {standard_task_runner.py:85} INFO - Job 135: Subtask from_local_to_gcs_task_2016
[2023-05-26T12:02:50.146+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=scheduled__2023-05-25T00:00:00+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T12:02:50.163+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 scheduled__2023-05-25T00:00:00+00:00 [running]> on host 335f5093005c
[2023-05-26T12:02:50.297+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_gcs_dag' AIRFLOW_CTX_TASK_ID='from_local_to_gcs_task_2016' AIRFLOW_CTX_EXECUTION_DATE='2023-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-25T00:00:00+00:00'
[2023-05-26T12:02:53.318+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-26T12:02:53.345+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=ingest_data_gcs_dag, task_id=from_local_to_gcs_task_2016, execution_date=20230525T000000, start_date=20230526T120249, end_date=20230526T120253
[2023-05-26T12:02:53.426+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-05-26T12:02:53.479+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
